apiVersion: v1
kind: Service
metadata:
  name: filestore
spec:
  selector:
    role: nfs
  ports:
    - protocol: TCP
      port: 80
# spec:
#   type: ExternalName
#   externalName: volumen.misitio.com
#   # external-service.svc.default.cluster
