apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: files-pvc
spec:
  accessModes:
      - ReadWriteMany
  storageClassName: ""
  volumeName: files-pv
  resources:
    requests:
      storage: 20Gi
