apiVersion: v1
kind: PersistentVolume
metadata:
  name: files-disk
  labels:
    volume: files
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /files
    server: 10.117.220.114
