apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: files
spec:
  resources:
    requests:
      storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  selector:
    matchLabels:
      volume: "files"
