apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: files
spec:
  resources:
    requests:
      storage: 20Gi
  accessModes:
    - ReadWriteMany
  selector:
    matchLabels:
      name: files-disk
