apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    micro: auth
spec:
  selector:
    matchLabels:
      micro: auth
  replicas: 2
  template:
    # Definición del POD
    metadata:
      name: auth
      labels:
        micro: auth
    spec:
      containers:
        - name: auth
          image: auth-micro/v1.1
          imagePullPolicy: Never
          resources:
            requests:
              cpu: "250m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "1024Mi"
          ports:
            - containerPort: 4000
              name: http
              protocol: TCP
          env:
            - name: PORT
              value: "4000"
          livenessProbe:
            httpGet:
              path: /health
              port: 4000
            initialDelaySeconds: 25
            timeoutSeconds: 1 # No debe durar la prueba más de un segundo
            periodSeconds: 15 # El periodo de tiempo
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 4000
            initialDelaySeconds: 5
            timeoutSeconds: 1 # No debe durar la prueba más de un segundo
            periodSeconds: 2 # El periodo de tiempo
            failureThreshold: 3