apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
  labels:
    micro: users
spec:
  selector:
    matchLabels:
      micro: users
  replicas: 1
  template:
    # Definición del POD
    metadata:
      name: users
      labels:
        micro: users
    spec:
      #restartPolicy: Never
      containers:
        - name: postgres
          image: postgres
          imagePullPolicy: IfNotPresent #Descargar la imagen si no esta en local
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "12345"
            - name: POSTGRES_DB
              value: "users"
          resources:
            limits:
              cpu: "125m"
              memory: "512Mi"
          ports:
            - containerPort: 5432
              protocol: TCP
          # volumeMounts:
          #   - mountPath: "/data"
          #     name: "db-data"
        - name: users
          image: gcr.io/backendadvancedtzuzulcode/microservices/users/v1.5
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "125m"
              memory: "128Mi"
            limits:
              cpu: "125m"
              memory: "1024Mi"
          ports:
            - containerPort: 4000
              name: http
              protocol: TCP
          env:
            - name: PORT
              value: "4000"
          livenessProbe:
            httpGet:
              path: /health
              port: 4000
            initialDelaySeconds: 25
            timeoutSeconds: 1 # No debe durar la prueba más de un segundo
            periodSeconds: 15 # El periodo de tiempo
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 4000
            initialDelaySeconds: 25
            timeoutSeconds: 1 # No debe durar la prueba más de un segundo
            periodSeconds: 2 # El periodo de tiempo
            failureThreshold: 3
      # volumes:
      #   - name: "db-data"
      #     hostPath:
      #       path: "/data/microservices/users"