apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: users-pvc
spec:
  accessModes:
      - ReadWriteMany
  storageClassName: ""
  volumeName: users-pv
  resources:
    requests:
      storage: 20Gi
