apiVersion: v1
kind: PersistentVolume
metadata:
  name: users-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /users
    server: 10.251.27.42 # IP de Filestore
